### ISSUE TITLE
Order of patterns in .gitignore matters

### ISSUE THREAD

**Issue by loomchild** [joeblau/gitignore.io#178] opened 2016-02-16 10:47 UTC
When generating gitignore for both Java and Gradle, the order of specifying parameters affects the file generated - it will simply contain the patters in specified order:

* https://www.gitignore.io/api/java%2Cgradle
* https://www.gitignore.io/api/gradle%2Cjava

However, only the first version is correct, since Gradle defines the following exception:

    !gradle-wrapper.jar

Java has the following pattern:

    *.jar

and Git applies patterns in .gitignore in order of appearance, so in the second case gradle-wrapper.jar can't be committed.

I think this seems a bit counter-intuitive in Git itself, since I'd expect negated patterns to be applied last, but I assume they have good reasons to rely on order. 

I'd be happy to help resolving this situation by submitting a pull request to gitignore.io, or alternatively follow it up at Git docs / mailing lists to understand the reasons for this behaviour. What do you think?

**Comment by joeblau** [comment] 2016-02-16 10:54
Very good catch.  Weighing the options; I think a programatic fix would be the best solution for users, but then we're left with the challenge of revising every template file and creating a dependency graph.  Alternatively, I think documentation would be the best alternative since solving this problem means you'll need a dependency tree of every .gitignore template (most which aren't managed by this repo).

What did you have in mind in terms of a PR?

**Comment by loomchild** [comment] 2016-02-16 11:08
I didn't think this through, but yeah, something like dependency graph.

Alternatively maybe detecting such conflicts in generated file and reordering them automatically - but then gitignore.io will need to start parsing and understanding .gitignore format. Maybe something simple as just putting all exceptions at the end would suffice.

**Comment by loomchild** [comment] 2016-02-16 12:21
Or perhaps, since the solution does not seem to be trivial, you prefer to work on it on your own (I don't know your codebase, and I don't know Node and JavaScript well). I'd personally keep it simple if possible - something like extracting negative patterns to the end of generated .gitingore (not sure if it fixes all problems) or storing a weight / dependency of each file.

**Comment by joeblau** [comment] 2016-02-16 14:12
I'm actually extremely busy on another project and I don't really have time to add any new major functionality.  The best course would be to add documentation describing what the issue is and then use this issue as a way for someone who has time to fix this properly to do so.

**Comment by loomchild** [comment] 2016-02-16 14:49
Well, I can happily invest some time, fix the bug and learn something. I will try to understand your code, think about a solution and post the results here within next couple of days. If anyone else has an idea how to proceed, feel free to share it.

**Comment by alirezaaa** [comment] 2016-03-03 22:09
I also faced this problem and I'm here to report that but someone already did. Thanks man. Please fix that.

**Comment by BookOfGreg** [comment] 2016-04-09 14:15
Would a part-way solution be to evaluate the patterns to check for collisions and to start with alert the user?

**Comment by joeblau** [comment] 2016-04-09 17:13
That could be, but it depends on which person thinks which project should have precedence.  The most simple thing would be to keep the gitignore templates in the order they are entered which means the user controls them.  via the command line this works correctly (`gi osx,swift` and `gi swift,osx`), but the Select 2 input box sorts by alphabetical order.

**Comment by joeblau** [comment] 2016-04-09 21:24
The order of the elements render in the order you type them into the Select2 box.  There is a bug in Select2 that automatically sorts the elements in alphabetical order.  Once there is a resolution to that, I'll be able to close this issue, but however you type your templates in the search box is how they will be ordered.

https://github.com/select2/select2/issues/3106

**Comment by loomchild** [comment] 2016-04-17 11:07
Personally I don't think it's a good solution to rely on order specified by the user. It would be much better if the generated .gitignore would _just work_ - I don't think it's an External Dependency problem.

I started looking into this problem and found [`generateFile`](https://github.com/joeblau/gitignore.io/blob/master/controllers/api/index.js#L65) function. I'd like to try changing it, but don't know how to run gitoignore.io locally. Is there a document how to do it, what are the requirements?

**Comment by joeblau** [comment] 2016-04-17 21:39
> Personally I don't think it's a good solution to rely on order specified by the user.

That's fine.  What do you propose to make it "just work"?

>  I'd like to try changing it, but don't know how to run gitoignore.io locally.

There are instructions on the repos [README.md](https://github.com/joeblau/gitignore.io/blob/master/README.md#install-locally)

**Comment by BookOfGreg** [comment] 2016-04-18 08:00
While I agree with the concept of it should just work, there are concerns with the artefact github.io outputs, such as which category do you put the resolved dependencies, how do you mark rules as missing from a block?
Maybe those two issues aren't concerns at all if you just take github.io as deterministic, as long as it returns the same file the content of the file doesn't matter as much.

What is your take on it @joeblau ? Should the output be self-descriptive, could github.io be more magical to fix these cases, or is there a happy middle where it can be magical while somehow telegraphing to the user what has been changed from defaults?

**Comment by loomchild** [comment] 2016-04-18 16:56
Thanks for the link @joeblau, I somehow missed this README section and I was looking in CONTRIBUTING file. However, this is more or less what I did and I am getting this error:

    npm install
    
    npm WARN peerDependencies The peer dependency grunt@0.4.x included from grunt-dustjs will no
    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 
    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
    npm WARN peerDependencies The peer dependency grunt@~0.4.1 included from grunt-config-dir will no

    npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency 

    npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.

    npm WARN deprecated lodash@0.9.2: Grunt needs your help! See https://github.com/gruntjs/grunt/issues/1403.

    npm WARN deprecated jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade

    npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

    npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.

    npm WARN optional dep failed, continuing fsevents@0.3.8

    npm WARN optional dep failed, continuing fsevents@0.3.8

    npm WARN optional dep failed, continuing fsevents@0.3.8

    npm WARN optional dep failed, continuing fsevents@0.3.8

    npm ERR! Linux 3.16.0-4-amd64

    npm ERR! argv "/home/loomchild/.nvm/versions/node/v4.4.3/bin/node" "/home/loomchild/.nvm/versions/node/v4.4.3/bin/npm" "install"

    npm ERR! node v4.4.3

    npm ERR! npm  v2.15.1

    npm ERR! code EPEERINVALID


    npm ERR! peerinvalid The package grunt@1.0.1 does not satisfy its siblings' peerDependencies requirements!

    npm ERR! peerinvalid Peer grunt-config-dir@0.3.2 wants grunt@~0.4.1

    npm ERR! peerinvalid Peer grunt-contrib-jshint@1.0.0 wants grunt@>=0.4.0

    npm ERR! peerinvalid Peer grunt-contrib-clean@1.0.0 wants grunt@>= 0.4.5

    npm ERR! peerinvalid Peer grunt-dustjs@1.3.0 wants grunt@0.4.x


    npm ERR! Please include the following file with any support request:

    npm ERR!     /home/loomchild/projekty/obce/gitignore.io/npm-debug.log

Is there a problem with my environment (wrong node or npm version for example)?

**Comment by joeblau** [comment] 2016-04-18 19:20
@BookOfGreg are you meaning to type "gitignore.io"? I'm open to suggestions; I have an idea, but I'm not sure it's straight forward.

@loomchild Which version of nodejs are you running?  How did you install node (Website, homebrew, apt-get) ?

**Comment by loomchild** [comment] 2016-04-18 23:04
I am using Node 4.4.3, npm 2.15.1, all installed via nvm. Initially it was installed via apt-get, but I removed it.

**Comment by joeblau** [comment] 2016-04-19 14:53
Hm.. I'm using 5.3 and i'm also on a Mac.  What flavor of Linux are you using?

**Comment by loomchild** [comment] 2016-04-19 15:47
Debian, I will give it a try with 5.x. I am not an expert in Nodejs, perhaps I am doing something completely wrong, does it work on Linux / Node 4 for someone else?

**Comment by loomchild** [comment] 2016-04-19 20:41
I confirm that it works with node 5.3, npm 3.3.12. I get a couple of warnings and one unmet peer dependency (see [full log](https://gist.github.com/loomchild/301ad800544f697671ea1554c42bcda0)), but it runs via node server.js.

**Comment by joeblau** [comment] 2016-04-20 00:14
Okay, those warnings should be fine.

**Comment by loomchild** [comment] 2016-04-20 12:01
Can I suggest splitting this issue into two distinct ones: 

1. Generated .gitignore file depends on order in which technologies were specified
2. When adding technologies, they are sorted by the JavaScript control, but still sent to the server in original order

2nd issue is an External Dependecy Bug and should be fixed in the select2 library.

I'd like to propose the solution to the 1st original issue. 

This can be done automagically, by extracting exception patterns (!...) from .gitginore files and placing them at the end of generated .gitignore. However, that effectively modifies the source gitignore files by splitting them in two parts, which could lead to hard to find bugs. This solution effectively tries to bypass the `git` behaviour, which should be discussed and addressed in `git` community itself, if anything.

Another solution would be to create dependency list for each .gitignore, creating a dependency graph. However, I believe that is an overkill in this situation.

I would like to propose a solution where we introduce a single file in data/ dir, called `order` for example, and put a list of .gitignore file names that require special treatment, in a defined order. During final .gitignore generation we could look at this file and reorder some of the technologies accordingly, leaving the rest in the original order (or some predefined deterministic one - alphabetical for example). This mechanism is less powerful than a real dependency graph, but in the end we need to have an absolute ordering in the resulting file (for example cycles cannot be expressed in absolute order file, but we don't really want cycles since they mean there's a deeper issue that needs addressing in gitignore files).

I could give it a try in the coming days / weeks, although I don't have much experience with nodejs, but I am eager to gain some.

What do you think?

**Comment by loomchild** [comment] 2016-04-24 11:27
Posted a proposed solution as a pull request #201. 

Example query that demonstrates how it works (Java and Gradle will be moved to the end of generated output):
http://localhost:8000/api/python%2Cgradle%2Cada%2Cjava%2Canjuta

**Closed** 2016-04-24 23:57 UTC
Labels: External Dependency Bug
