### ISSUE TITLE
No way to re-order ignores

### ISSUE THREAD

**Issue by theoriginalbit** [joeblau/gitignore.io#220] opened 2016-07-12 03:06 UTC
Certain `.gitignore` files have a particular order they should appear in. For example, the `Umbraco.gitignore` rules must appear after the `VisualStudio.gitignore` rules, because of [this](https://github.com/github/gitignore/blob/master/Umbraco.gitignore#L14).

A way to re-order what's been selected would be great!

**Comment by theoriginalbit** [comment] 2016-07-12 03:10
Oh, I should mention that re-ordering does work when added directly to the URL. But the main UI will produce the following URL `https://www.gitignore.io/api/umbraco,visualstudio` when the URL that is actually needed would be `https://www.gitignore.io/api/visualstudio,umbraco`

**Comment by joeblau** [comment] 2016-07-12 14:57
This is a duplicate of #178 - There is a file in  `./data/order` that you can modify to specify that umbraco depends on visual studio.

All you need to do is specify the dependencies in order:

```sh
visual studio
umbrage
```

And the correct ordering will be respected across the API.

**Closed** 2016-07-12 14:58 UTC
