### ISSUE TITLE
Has problem with option for Gradle build tool

### ISSUE THREAD

**Issue by donhuvy** [joeblau/gitignore.io#406] opened 2018-06-25 01:39 UTC
# Issue Template

## Frequently Asked Questions

https://www.gitignore.io/api/java%2Cgradle%2Cintellij%2Ball

**Q:** How do I submit a new <code>.gitignore</code> templates?  
**A:** Please submit all new templates to [@dvcs/gitignore](https://github.com/dvcs/gitignore).

**Q:** How do I suggest modifications to existing `.gitignore` templates?  
**A:** Modifictions should come in the form of pull requests at [@dvcs/gitignore](https://github.com/dvcs/gitignore).

**Q:** Why don't Gitignore.io's templates don't look exactly like the templates on [@github/gitignore](https://github.com/github/gitignore)?  
**A:** Gitignore.io tried to maintain parity with [@github/gitignore](https://github.com/github/gitignore), but GitHub's template list doesn't include many languages, operating systems, and IDE's that developers use.  Gitignore.io's template list has over 100 more templatess than GitHub's.

**Q:** Why is my local site empty?  
**A:** When the repository is cloned, the `--recursive` flag is necessary.  gitignore.io uses @dvcs/gitignore as it's data source.  If  the repo isn't cloned recursively, templates will be missing.

### Development Environment:

- [x ] Machine (Local, Container, Virtual): Local
- [ z] Operating System (Name/Version): Windows 10 pro x64
- [ x] Web Browser (Name/Version): Google Chrome 67
- [ ] Vapor Version:
- [ ] Swift Version:

**Comment by joeblau** [comment] 2018-06-25 01:46
Duplicate of #405.
Once this build clears, I'll update production.

https://travis-ci.org/joeblau/gitignore.io/builds/396215913

**Closed by joeblau** 2018-06-25 01:46 UTC
Labels: Duplicate

**Comment by joeblau** [comment] 2018-06-25 01:47
This is fixed now, go back to https://www.gitingore.io and try again please.
